name: ⚙️ Build

on: workflow_call

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: ./.github/actions/nodejs

            -   name: Build
                run: npx nx affected --target=build --base=origin/main --parallel
