name: ⚙️ Lint

on: workflow_call

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: ./.github/actions/nodejs

            -   name: Lint
                run: npx nx affected --target=lint --quiet=true --base=origin/main --parallel
