name: ⚙️ Tests

on: workflow_call

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: ./.github/actions/nodejs

            -   name: Test
                run: npx nx affected --target=test --configuration=ci --base=origin/main --parallel
